
name: AdrianSouza-FernandoCardosoAtv

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Executar toda meia-noite aos sábados

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o código
        uses: actions/checkout@v2

      - name: Exibir data e hora do push
        run: echo "Data e Hora do Push: $(date)"

      - name: Exibir usuário do push
        run: echo "Usuário do Push: ${{ github.actor }}"

      - name: Calcular 2 + 2 no terminal
        run: echo "2 + 2 = $((2 + 2))"

      - name: Listar arquivos no repositório
        run: ls -l

      - name: Contar arquivos HTML no repositório
        run: echo "Arquivos HTML: $(ls *.html | wc -l)"

      - name: Criar um arquivo README
        run: echo "Este é um exemplo de repositório com GitHub Actions!" > README.md

      - name: Agendar execução apenas à noite
        if: ${{ github.event_name == 'schedule' }}
        run: echo "Executando apenas durante a noite!"

      - name: Agendar execução apenas aos sábados
        if: ${{ github.event_name == 'schedule' }}
        run: echo "Executando apenas aos sábados!"

      - name: Verificar arquivos maiores que 100KB
        run: |
          for file in *; do
            if [ -f "$file" ] && [ $(stat -c %s "$file") -gt 102400 ]; then
              echo "Alerta: O arquivo $file é maior que 100KB"
            fi
          done

      - name: Action com múltiplos steps - Data, Usuário, e Arquivos HTML/CSS/JS
        run: |
          echo "Data e Hora do Push: $(date)"
          echo "Usuário do Push: ${{ github.actor }}"
          html_files=$(ls *.html | wc -l)
          css_files=$(ls *.css | wc -l)
          js_files=$(ls *.js | wc -l)
          echo "Arquivos HTML: $html_files"
          echo "Arquivos CSS: $css_files"
          echo "Arquivos JS: $js_files"

      - name: Agendamento: Contar arquivos à meia-noite
        if: ${{ github.event_name == 'schedule' }}
        run: |
          total_files=$(ls | wc -l)
          echo "Total de arquivos no repositório: $total_files"
