name: Multi-step (sequence)
on:
  push:

jobs:
  multistep-seq:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Data (SP)
        run: |
          echo "Data/Hora (São Paulo):"
          TZ="America/Sao_Paulo" date +"%Y-%m-%d %H:%M:%S %Z"

      - name: user
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Pusher name: ${{ github.event.pusher.name || 'não disponível' }}"

      - name: alterados em sequencia
        run: |
          echo "Arquivos no último commit (ordem do git diff):"
          git fetch --depth=2 origin ${{ github.ref }}
          PREV="${{ github.sha }}^"
          git --no-pager diff --name-only "${PREV}" "${{ github.sha }}" || git --no-pager show --name-only --pretty="" "${{ github.sha }}"
      - name: Contar .html .css .js 
        run: |
          LIST=$(git --no-pager diff --name-only "${{ github.sha }}^" "${{ github.sha }}" || git --no-pager show --name-only --pretty="" "${{ github.sha }}")
          echo "$LIST"
          HTML=$(echo "$LIST" | grep -i '\.html$' | wc -l || true)
          CSS=$(echo "$LIST" | grep -i '\.css$' | wc -l || true)
          JS=$(echo "$LIST" | grep -i '\.js$' | wc -l || true)
          echo "Enviados neste commit — HTML: $HTML | CSS: $CSS | JS: $JS"
